language: ruby

before_install:
  - gem update --system
  - gem install bundler -v '< 2'
env:
  - RAILS_ENV=test
  
script:
  - bin/rails db:create
  - bin/rails db:migrate
  - bin/rspec

services:
  - postgresql

addons:
  postgresql: "9.6"

cache:
  directories:
    - vendor/bundle