development: &default
  adapter: postgresql
  database: todo-api_development
  encoding: unicode
  username: postgres
  password:
  port: 5432
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: todo-api_test

production:
  <<: *default
  database: todo-api_production
  username: todo-api
  password: <%= ENV['TODO-API_DATABASE_PASSWORD'] %>
